dataset: cifar100
aa: null
batch_size: 128
color_jitter: 0.0
cutout_length: 16
decay_by_epoch: false
decay_epochs: 3
decay_rate: 0.967
drop: 0.0
epochs: 250
log_interval: 50
lr: 0.1
smoothing: 0.0
min_lr: 1.0e-06
model_ema: false
model_ema_decay: 0.9998
momentum: 0.9
opt: sgd
opt_betas: null
opt_eps: 1.0e-08
remode: const
reprob: 0.0
sched: cosine
seed: 1
warmup_epochs: 0
warmup_lr: 0.2
weight_decay: 1.0e-04
workers: 4
sgd_no_nesterov: True
opt_no_filter: True
# dyrep
dyrep: False
dyrep_adjust_interval: 15
dyrep_recal_bn_every_epoch: False
dyrep_max_adjust_epochs: 500
teacher_ckpt: 'exp_im_teachers/cifar100_ResNet50/best.pth.tar'
teacher_model: 'cifar_ResNet50'
teacher_pretrained: True
train_feature_space_diffsion: False
test_feature_space_diffsion: False
test_student_model: True
train_transfer_head: False
student_pretrained: False
pretrained_ckpt: ''

generative_prior_kwargs:
  generative_prior_ckpt: 'exp_im_teachers/cifar100_ResNet50_LD/best.pth.tar'
  generative_prior_model: 'latentdiffusion'
  uncertain_teacher_diffusion_steps: [50, 30]
  guidance_scale: [0.3, 0.5]
  frozen_gen_prior: True
  use_ae: True
  ae_channels: 1024
  diff_loss_weight: 1.0
  ae_loss_weight: 1.0
  feature_guidance: True
  classifier_guidance: True
  add_logits_loss: True
  is_reverse_sched: False
val_loss_monitor_metric: top1 #top5, test_loss
val_loss_monitor_mode: max
kd: ''


